title = "Gitleaks configuration"

[allowlist]
description = "Docs, binaries, local dev env, and build artifacts."
paths = [
  '''.*\.lock$''',
  '''.*\.svg$''',
  '''.*\.png$''',
  '''.*\.jpg$''',
  '''.*\.jpeg$''',
  '''.*\.gif$''',
  '''.*\.pdf$''',
  '''.*\.min\.js$''',
  '''.*\.map$''',
  '''\.next/''',
  '''\.env\.local$''',
  '''\.env\..*\.local$''',
  '''out/''',
  '''/data/''',
  '''playwright-report/''',
  '''test-results/'''
]
